import { atom } from 'recoil';

export const reviewUpdateState = atom({
  key: 'reviewUpdateState',
  default: {
    reviewId: '',
    userId: '',
    totalRate: 0,
    transRate: 0,
    manageRate: 0,
    infraRate: 0,
    lifeRate: 0,
    title: '',
    description: '',
    jibun: '',
    pos: '',
    floorsCount: '',
    pyungCount: '',
    roomInfo: '',
    roomOption: '',
    contractTypeId: '1',
    startDate: '',
    endDate: '',
    images: [],
  },
    // default: {
    //   reviewId: 10009,
    //   userId: 10000,
    //   totalRate: 5,
    //   transRate: 4,
    //   manageRate: 3,
    //   infraRate: 2,
    //   lifeRate: 1,
    //   title: '제목',
    //   description: '내용',
    //   jibun: '주소',
    //   pos: '37.4985356558395,127.032615766508',
    //   floorsCount: '10',
    //   pyungCount: '5',
    //   roomInfo: 'ㅇㅇㅇㅇㅇ',
    //   roomOption: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',
    //   contractTypeId: '2',
    //   startDate: '2024-10-05',
    //   endDate: '2024-12-31',
    //   images: [],
    // },
});
