import _ from 'lodash';
import { useRecoilState } from 'recoil';
import { searchState } from '../../recoil/searchState';
import './GuDongList.scss';

const list = [
  { label: '전체', value: '' },
  {
    label: '강남구',
    value: '강남구',
    dongList: [
      { label: '전체', value: '' },
      { label: '개포동', value: '개포동' },
      { label: '논현동', value: '논현동' },
      { label: '대치동', value: '대치동' },
      { label: '도곡동', value: '도곡동' },
      { label: '삼성동', value: '삼성동' },
      { label: '세곡동', value: '세곡동' },
      { label: '수서동', value: '수서동' },
      { label: '신사동', value: '신사동' },
      { label: '압구정', value: '압구정' },
      { label: '역삼동', value: '역삼동' },
      { label: '울현동', value: '울현동' },
      { label: '일원동', value: '일원동' },
      { label: '자곡동', value: '자곡동' },
      { label: '청담동', value: '청담동' },
    ],
  },
  {
    label: '강동구',
    value: '강동구',
    dongList: [
      { label: '전체', value: '' },
      { label: '강일동', value: '강일동' },
      { label: '고덕동', value: '고덕동' },
      { label: '길동', value: '길동' },
      { label: '둔촌동', value: '둔촌동' },
      { label: '명일동', value: '명일동' },
      { label: '상일동', value: '상일동' },
      { label: '성내동', value: '성내동' },
      { label: '암사동', value: '암사동' },
      { label: '천호동', value: '천호동' },
    ],
  },
  {
    label: '강북구',
    value: '강북구',
    dongList: [
      { label: '전체', value: '' },
      { label: '미아동', value: '미아동' },
      { label: '번동', value: '번동' },
      { label: '수유동', value: '수유동' },
      { label: '우이동', value: '우이동' },
    ],
  },
  {
    label: '강서구',
    value: '강서구',
    dongList: [
      { label: '전체', value: '' },
      { label: '가양동', value: '' },
      { label: '개화동', value: '' },
      { label: '공항동', value: '' },
      { label: '과해동', value: '' },
      { label: '내발산동', value: '' },
      { label: '등촌동', value: '' },
      { label: '마곡동', value: '' },
      { label: '방화동', value: '' },
      { label: '염창동', value: '' },
      { label: '오곡동', value: '' },
      { label: '오쇠동', value: '' },
      { label: '외발산동', value: '' },
      { label: '화곡동', value: '' },
    ],
  },
  {
    label: '관악구',
    value: '관악구',
    dongList: [
      { label: '전체', value: '' },
      { label: '남현동', value: '' },
      { label: '봉천동', value: '' },
      { label: '신림동', value: '' },
    ],
  },
  {
    label: '광진구',
    value: '광진구',
    dongList: [
      { label: '전체', value: '' },
      { label: '광장동', value: '' },
      { label: '구의동', value: '' },
      { label: '군자동', value: '' },
      { label: '능동', value: '' },
      { label: '자양동', value: '' },
      { label: '중곡동', value: '' },
      { label: '화양동', value: '' },
    ],
  },
  {
    label: '구로구',
    value: '구로구',
    dongList: [
      { label: '전체', value: '' },
      { label: '가리봉동', value: '' },
      { label: '개봉동', value: '' },
      { label: '고척동', value: '' },
      { label: '구로동', value: '' },
      { label: '궁동', value: '' },
      { label: '신도림동', value: '' },
      { label: '오류동', value: '' },
      { label: '온수동', value: '' },
      { label: '천왕동', value: '' },
      { label: '항동', value: '' },
    ],
  },
  {
    label: '금천구',
    value: '금천구',
    dongList: [
      { label: '전체', value: '' },
      { label: '가산동', value: '' },
      { label: '독산동', value: '' },
      { label: '시흥동', value: '' },
    ],
  },
  {
    label: '노원구',
    value: '노원구',
    dongList: [
      { label: '전체', value: '' },
      { label: '공릉동', value: '' },
      { label: '상계동', value: '' },
      { label: '월계동', value: '' },
      { label: '중계동', value: '' },
      { label: '하계동', value: '' },
    ],
  },
  {
    label: '도봉구',
    value: '도봉구',
    dongList: [
      { label: '전체', value: '' },
      { label: '도봉동', value: '' },
      { label: '방학동', value: '' },
      { label: '쌍문동', value: '' },
      { label: '창동', value: '' },
    ],
  },
  {
    label: '동대문구',
    value: '동대문구',
    dongList: [
      { label: '전체', value: '' },
      { label: '답십리동', value: '' },
      { label: '신설동', value: '' },
      { label: '용두동', value: '' },
      { label: '이문동', value: '' },
      { label: '장인동', value: '' },
      { label: '전농동', value: '' },
      { label: '제기동', value: '' },
      { label: '청량리동', value: '' },
      { label: '회기동', value: '' },
      { label: '휘경동', value: '' },
    ],
  },
  {
    label: '동작구',
    value: '동작구',
    dongList: [
      { label: '전체', value: '' },
      { label: '노량진동', value: '' },
      { label: '대방동', value: '' },
      { label: '동작동', value: '' },
      { label: '본동', value: '' },
      { label: '사당동', value: '' },
      { label: '상도1동', value: '' },
      { label: '상도동', value: '' },
      { label: '신대방동', value: '' },
      { label: '흑석동', value: '' },
    ],
  },
  {
    label: '마포구',
    value: '마포구',
    dongList: [
      { label: '전체', value: '' },
      { label: '공덕동', value: '' },
      { label: '구수동', value: '' },
      { label: '노고산동', value: '' },
      { label: '당인동', value: '' },
      { label: '대홍동', value: '' },
      { label: '도화동', value: '' },
      { label: '동교동', value: '' },
      { label: '마포동', value: '' },
      { label: '망원동', value: '' },
      { label: '상수동', value: '' },
      { label: '상암동', value: '' },
      { label: '서교동', value: '' },
      { label: '성산동', value: '' },
      { label: '신공덕동', value: '' },
      { label: '신수동', value: '' },
      { label: '신정동', value: '' },
      { label: '아현동', value: '' },
      { label: '연남동', value: '' },
      { label: '염리동', value: '' },
      { label: '용강동', value: '' },
      { label: '중동', value: '' },
      { label: '창전동', value: '' },
      { label: '토정동', value: '' },
      { label: '하중동', value: '' },
      { label: '합정동', value: '' },
      { label: '현석동', value: '' },
    ],
  },
  {
    label: '서대문구',
    value: '서대문구',
    dongList: [
      { label: '전체', value: '' },
      { label: '남가좌동', value: '' },
      { label: '냉천동', value: '' },
      { label: '대신동', value: '' },
      { label: '대현동', value: '' },
      { label: '미근동', value: '' },
      { label: '봉원동', value: '' },
      { label: '북가좌동', value: '' },
      { label: '북아현동', value: '' },
      { label: '신촌동', value: '' },
      { label: '연희동', value: '' },
      { label: '영천동', value: '' },
      { label: '옥천동', value: '' },
      { label: '창천동', value: '' },
      { label: '천연동', value: '' },
      { label: '충정로', value: '' },
      { label: '합동', value: '' },
      { label: '현저동', value: '' },
      { label: '홍은동', value: '' },
      { label: '홍제동', value: '' },
    ],
  },
  {
    label: '서초구',
    value: '서초구',
    dongList: [
      { label: '전체', value: '' },
      { label: '내곡동', value: '' },
      { label: '반포동', value: '' },
      { label: '방배동', value: '' },
      { label: '서초동', value: '' },
      { label: '신원동', value: '' },
      { label: '양재동', value: '' },
      { label: '염곡동', value: '' },
      { label: '우면동', value: '' },
      { label: '원지동', value: '' },
      { label: '잠원동', value: '' },
    ],
  },
  {
    label: '성동구',
    value: '성동구',
    dongList: [
      { label: '전체', value: '' },
      { label: '금호동', value: '' },
      { label: '도선동', value: '' },
      { label: '마장동', value: '' },
      { label: '사근동', value: '' },
      { label: '상왕십리동', value: '' },
      { label: '성수동', value: '' },
      { label: '송정동', value: '' },
      { label: '옥수동', value: '' },
      { label: '용답동', value: '' },
      { label: '응봉동', value: '' },
      { label: '하왕십리동', value: '' },
      { label: '행당동', value: '' },
      { label: '홍의동', value: '' },
    ],
  },
  {
    label: '성북구',
    value: '성북구',
    dongList: [
      { label: '전체', value: '' },
      { label: '길음동', value: '' },
      { label: '돈암동', value: '' },
      { label: '동선동', value: '' },
      { label: '동소문동', value: '' },
      { label: '보문동', value: '' },
      { label: '삼선동', value: '' },
      { label: '상월곡동', value: '' },
      { label: '석관동', value: '' },
      { label: '성북동', value: '' },
      { label: '안암동', value: '' },
      { label: '장위동', value: '' },
      { label: '정릉동', value: '' },
      { label: '종암동', value: '' },
      { label: '하월곡동', value: '' },
    ],
  },
  {
    label: '송파구',
    value: '송파구',
    dongList: [
      { label: '전체', value: '' },
      { label: '가락동', value: '' },
      { label: '거여동', value: '' },
      { label: '마천동', value: '' },
      { label: '문정동', value: '' },
      { label: '방이동', value: '' },
      { label: '삼전동', value: '' },
      { label: '석촌동', value: '' },
      { label: '송파동', value: '' },
      { label: '신천동', value: '' },
      { label: '오금동', value: '' },
      { label: '잠실동', value: '' },
      { label: '장지동', value: '' },
      { label: '풍납동', value: '' },
    ],
  },
  {
    label: '양천구',
    value: '양천구',
    dongList: [
      { label: '전체', value: '' },
      { label: '목동', value: '' },
      { label: '신월동', value: '' },
      { label: '신정동', value: '' },
    ],
  },
  {
    label: '영등포구',
    value: '영등포구',
    dongList: [
      { label: '전체', value: '' },
      { label: '당산동', value: '' },
      { label: '대림동', value: '' },
      { label: '도림동', value: '' },
      { label: '문래동', value: '' },
      { label: '신길동', value: '' },
      { label: '양평동', value: '' },
      { label: '양화동', value: '' },
      { label: '여의도동', value: '' },
      { label: '영등포동', value: '' },
    ],
  },
  {
    label: '용산구',
    value: '용산구',
    dongList: [
      { label: '전체', value: '' },
      { label: '갈월동', value: '' },
      { label: '남ㅁ영동', value: '' },
      { label: '도원동', value: '' },
      { label: '동빙고동', value: '' },
      { label: '동자동', value: '' },
      { label: '문배동', value: '' },
      { label: '보광동', value: '' },
      { label: '산천동', value: '' },
      { label: '서계동', value: '' },
      { label: '서빙고동', value: '' },
      { label: '신계동', value: '' },
      { label: '신창동', value: '' },
      { label: '용문동', value: '' },
      { label: '용산동', value: '' },
      { label: '원효로', value: '' },
      { label: '이촌동', value: '' },
      { label: '이태원동', value: '' },
      { label: '주성동', value: '' },
      { label: '청암동', value: '' },
      { label: '청파동', value: '' },
      { label: '한강로', value: '' },
      { label: '한남동', value: '' },
      { label: '효창동', value: '' },
      { label: '후암동', value: '' },
    ],
  },
  {
    label: '은평구',
    value: '은평구',
    dongList: [
      { label: '전체', value: '' },
      { label: '갈현동', value: '' },
      { label: '구산동', value: '' },
      { label: '녹번동', value: '' },
      { label: '대조동', value: '' },
      { label: '불광동', value: '' },
      { label: '수색동', value: '' },
      { label: '신사동', value: '' },
      { label: '역촌동', value: '' },
      { label: '용암동', value: '' },
      { label: '증산동', value: '' },
      { label: '진광동', value: '' },
    ],
  },
  {
    label: '종로구',
    value: '종로구',
    dongList: [
      { label: '전체', value: '' },
      { label: '가회동', value: '' },
      { label: '견지동', value: '' },
      { label: '경운동', value: '' },
      { label: '계동', value: '' },
      { label: '공평동', value: '' },
      { label: '관수동', value: '' },
      { label: '관철동', value: '' },
      { label: '관훈동', value: '' },
      { label: '교남동', value: '' },
      { label: '교북동', value: '' },
      { label: '구기동', value: '' },
      { label: '궁정동', value: '' },
      { label: '권농동', value: '' },
      { label: '낙원동', value: '' },
      { label: '내수동', value: '' },
      { label: '내자동', value: '' },
      { label: '누상동', value: '' },
      { label: '누하동', value: '' },
      { label: '당주동', value: '' },
      { label: '도렴동', value: '' },
      { label: '돈의동', value: '' },
      { label: '동숭동', value: '' },
      { label: '명륜', value: '' },
      { label: '묘동', value: '' },
      { label: '무악동', value: '' },
      { label: '봉익동', value: '' },
      { label: '부암동', value: '' },
      { label: '사간동', value: '' },
      { label: '사직동', value: '' },
      { label: '삼청동', value: '' },
      { label: '서린동', value: '' },
      { label: '세종로', value: '' },
      { label: '소격동', value: '' },
      { label: '송월동', value: '' },
      { label: '송현동', value: '' },
      { label: '수송동', value: '' },
      { label: '송인동', value: '' },
      { label: '신교동', value: '' },
      { label: '신문로', value: '' },
      { label: '신영동', value: '' },
      { label: '안국동', value: '' },
      { label: '연건동', value: '' },
      { label: '연지동', value: '' },
      { label: '예지동', value: '' },
      { label: '옥인동', value: '' },
      { label: '와룡동', value: '' },
      { label: '운니동', value: '' },
      { label: '원남동', value: '' },
      { label: '원서동', value: '' },
      { label: '이화동', value: '' },
      { label: '익선동', value: '' },
      { label: '인사동', value: '' },
      { label: '인의동', value: '' },
      { label: '장사동', value: '' },
      { label: '재동', value: '' },
      { label: '적선동', value: '' },
      { label: '종로', value: '' },
      { label: '중학동', value: '' },
      { label: '창성동', value: '' },
      { label: '창신동', value: '' },
      { label: '청운동', value: '' },
      { label: '청진동', value: '' },
      { label: '체부동', value: '' },
      { label: '충신동', value: '' },
      { label: '통의동', value: '' },
      { label: '통인동', value: '' },
      { label: '팔판동', value: '' },
      { label: '평동', value: '' },
      { label: '평창동', value: '' },
      { label: '필운동', value: '' },
      { label: '행촌동', value: '' },
      { label: '혜화동', value: '' },
      { label: '홍지동', value: '' },
      { label: '홍파동', value: '' },
      { label: '화동', value: '' },
      { label: '효자동', value: '' },
      { label: '효제동', value: '' },
      { label: '훈정동', value: '' },
    ],
  },
  {
    label: '중구',
    value: '중구',
    dongList: [
      { label: '전체', value: '' },
      { label: '광희동', value: '' },
      { label: '남대문로', value: '' },
      { label: '남산동', value: '' },
      { label: '남창동', value: '' },
      { label: '남학동', value: '' },
      { label: '다동', value: '' },
      { label: '만리동', value: '' },
      { label: '명동', value: '' },
      { label: '무교동', value: '' },
      { label: '무학동', value: '' },
      { label: '묵적동', value: '' },
      { label: '방산동', value: '' },
      { label: '봉래동', value: '' },
      { label: '북창동', value: '' },
      { label: '산림동', value: '' },
      { label: '삼각동', value: '' },
      { label: '서소문동', value: '' },
      { label: '소공동', value: '' },
      { label: '수표동', value: '' },
      { label: '수하동', value: '' },
      { label: '순화동', value: '' },
      { label: '신당동', value: '' },
      { label: '쌍림동', value: '' },
      { label: '예관동', value: '' },
      { label: '예장동', value: '' },
      { label: '오장동', value: '' },
      { label: '을지로', value: '' },
      { label: '의주로', value: '' },
      { label: '인현동', value: '' },
      { label: '입정동', value: '' },
      { label: '장교동', value: '' },
      { label: '장충동', value: '' },
      { label: '저동', value: '' },
      { label: '정동', value: '' },
      { label: '주교동', value: '' },
      { label: '주자동', value: '' },
      { label: '중림동', value: '' },
      { label: '초동', value: '' },
      { label: '충무로', value: '' },
      { label: '충정로', value: '' },
      { label: '태평로', value: '' },
      { label: '필동', value: '' },
      { label: '황학동', value: '' },
      { label: '회현동', value: '' },
      { label: '흥인동', value: '' },
    ],
  },
  {
    label: '중랑구',
    value: '중랑구',
    dongList: [
      { label: '전체', value: '' },
      { label: '망우동', value: '' },
      { label: '면목동', value: '' },
      { label: '묵동', value: '' },
      { label: '상봉동', value: '' },
      { label: '신내동', value: '' },
      { label: '중화동', value: '' },
    ],
  },
];

function GuDongList({ gudongType, onClickGudongType }) {
  const [search, setSearch] = useRecoilState(searchState);
  const { gu } = search;
  const items =
    gudongType === 'gu' ? list : _.find(list, { label: gu }).dongList;

  const handleClickItem = (item) => {
    if (gudongType === 'gu') {
      setSearch({
        ...search,
        searchType: 'filter',
        gu: item.value,
        dong: '',
      });
    } else {
      setSearch({
        ...search,
        searchType: 'filter',
        dong: item.label,
      });
    }
    onClickGudongType('');
  };

  return (
    <div className="gudong__list__popup__container">
      {items != null &&
        items.map((item, index) => {
          return (
            <div
              className="gudong__list__popup__item"
              key={index}
              onClick={() => handleClickItem(item)}
            >
              {item.label}
            </div>
          );
        })}
    </div>
  );
}

export default GuDongList;
